# Generated by Django 4.2.6 on 2023-10-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='selected_language',
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
